#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev# 激活开发环境配置

emp:
  name: babosa-bjj
---

server:
  port: 8011 #端口号

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     # mybatis配置文件所在路径
  type-aliases-package: com.babosa.springcloud.entities  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml    # mapper映射文件

spring:
  profiles: dev # 开发环境
  application:
    name: babosa-microservice-product-config #服务器名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource       # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql驱动包
    url: jdbc:mysql://118.190.27.59:33306/springcloud_db02?serverTimezone=GMT%2B8  # 数据库名称
#     url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                 # 数据库连接池的最小维持连接数
      initial-size: 5               # 初始化连接数
      max-total: 5                # 最大连接数
      max-wait-millis: 150            # 等待连接获取的最大超时时间


eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://118.190.27.59:6001/eureka/
#       defaultZone: http://babosa6001.com:6001/eureka/

---

server:
  port: 8011 #端口号

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     # mybatis配置文件所在路径
  type-aliases-package: com.babosa.springcloud.entities  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml    # mapper映射文件

spring:
  profiles: prod # 开发环境
  application:
    name: babosa-microservice-product-config-rabbitMQ-bus1 #服务器名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource       # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql驱动包
    url: jdbc:mysql://118.190.27.59:33306/springcloud_db03?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                 # 数据库连接池的最小维持连接数
      initial-size: 5               # 初始化连接数
      max-total: 5                # 最大连接数
      max-wait-millis: 150            # 等待连接获取的最大超时时间

 
eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://118.190.27.59:6001/eureka/
   
#保存时注意，选择 UTF-8 保存
